[workspace]

members = [
    "object_capabilities",
    "object_diecup",
    "object_entrypoint",
    "prelude",
    "token_capabilities",
    "token_diecup",
    "token_entrypoint",
    "facet_entrypoint",
]
