[package]
name = "token_diecup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
token_capabilities = { path = "../token_capabilities" }
prelude = { path = "../prelude" }
rand = "0.8.5"
