[package]
name = "trusted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capability_api = { path = "../capability_api" }
diecup = { path = "../diecup" }
